### ISSUE TITLE
ErrorHandler issue

### ISSUE THREAD

**Issue by SoulUchiha** [FiredragonPlayz/Discordjs-v13-Handler#3]
TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (/home/runner/CyR-v2/Events/ErrorHandler.js:113:14)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at doEmitWarning (node:internal/process/warning:77:11) uncaughtException
/home/runner/CyR-v2/Events/ErrorHandler.js:77
    return d.send({
             ^

TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (/home/runner/CyR-v2/Events/ErrorHandler.js:77:14)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
repl process died unexpectedly: exit status 7

**Comment by SoulUchiha** [comment]
ok its fixed
